### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by fahseltc** [calvarado194/celeste-bingo#9]
I think the tool could use some options area where you could set various toggles. For example:
"No berries" (exclude all the berry tasks)
"No ALL" (meaning no "all berries" tasks or "all feathers" tasks or similar. Could make runs shorter.)
"No PICO" (no pico8 tasks)

Im sure there are a ton more options people will request.

**Comment by calvarado194** [comment]
We should merge this issue with #1

**Comment by calvarado194** [comment]
Best way to execute this is by adding flags as a query URL, and giving tasks extra flag information.
At the moment of fetching the task library, we can filter tasks with flags and prevent them from showing up.

Expanding upon this, we can keep a separate task library for any% cheat or other categories, and fetch from their respective list when possible. This would allow for bigger diversity within each category.

**Comment by calvarado194** [comment]
Implemented in #17
